languageCode = "en-us"
title = "Habib Belaribi"
baseURL = "/"
theme = "hugo-theme-massively"
googleanalytics = "UA-162245098-1"
disqusShortname = ""
disableKinds = ["taxonomy", "taxonomyTerm", "section"]
	

[params.favicon]
  # set below parameter to define a favicon
	favicon = "favicon.ico"
	mastodon="mastodon.png"
	stackoverflow="stackoverflow.png"
  # set to change date format
  # dateFormat = "2.1.2006"

# Below parameters can be set to override default post settings
#[params.posts]
     folderName = "/post"
     pageSize = "0"
     featuredPost = true
     paginationPages = 0
     showFirstLast = true
 
[languages]
[languages.en]
  languageName = "English"
  title = "Who is speaking?"
[languages.fr]
  languageName = "Français"
  title = "Qui parle?"
#[languages.es]
  #languageName = "Español"
  #title = "Massively - Versión Español"


	

